title: ""        # leave it empty to remove the text
description: ""  # optional: remove description as well
theme: minima
baseurl: ""  # Leave this blank for GitHub Pages
url: "https://Winter777ex.github.io"